TDE/libkdcraw: 100% of translation progress while update README.md in TDE dir
AOSC-Dev/translations pull request #48
Opened 2023-05-11 13:40 UTC by LWanTao

1. 100% of translation progress for libkdcraw component, after fetching upstream updated at 2023.06.28.
2. Update README.md in TDE dir.

2023-05-14 07:36 UTC, MingcongBai requested changes

2023-05-14 07:36 UTC, MingcongBai commented on TDE/libraries-libkdcraw-zh_Hans.po
> +"<qt><p>无法找到 <b>%1</b> 可执行文件：<br>需要此二进制程序以支持RAW文件格式。"
这里用“找不到”可能会干练一些；注意中英文之间留空格：

找不到可执行文件 <b>%1<b>：需要该可执行文件提供 RAW 支持。

2023-05-14 07:36 UTC, MingcongBai commented on TDE/libraries-libkdcraw-zh_Hans.po
> +"您可以继续，但是您将无法处理任何RAW格式图像。请确认您的计算机中是否已经安装 "
建议多读读自己写的东西，你感觉这读起来像中文还是英文？

2023-05-14 07:36 UTC, MingcongBai commented on TDE/libraries-libkdcraw-zh_Hans.po
> +"您可以继续，但是您将无法处理任何RAW格式图像。请确认您的计算机中是否已经安装 "
本地化过程中，只要确保内容和必要信息一致，句式是可以进行调整的。

2023-05-14 07:36 UTC, MingcongBai commented on TDE/libraries-libkdcraw-zh_Hans.po
> +"序的 %2 版本。此版本过旧以至于无法正常运行。您可以继续，但是您将无法处理任何"
“以至于”也是典型的英式中文

2023-05-14 07:36 UTC, MingcongBai commented on TDE/libraries-libkdcraw-zh_Hans.po
> +msgstr "黑色："
这里指的应该是黑点

2023-05-14 07:36 UTC, MingcongBai commented on TDE/libraries-libkdcraw-zh_Hans.po
> +msgstr "白色："
同样地，这里大概是白点

2023-07-06 00:35 UTC, MingcongBai requested changes

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"的支持。如果继续，您将无法处理任何 RAW 格式图像。请检查 libkdcraw 软件包在您"
- 可执行文件 => 命令；可执行文件这个词让人感觉这个文件可以在任意地方。
- 如果继续，您将无法处理任何 RAW 格式图像 => 您将无法处理 RAW 格式图像。

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<qt><p>可执行文件 <b>%1</b> 不是最新版本：<br> 在您的计算机中已找到此二进制程"
可执行文件 %1 => %1 命令的可执行文件

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "16 位颜色深度"
“色深”即可

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p>如果启用，所有的 RAW 文件将以 16 位颜色深度解码，并且使用线性伽玛曲线。为"
- 所有的 => 所有

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "请不要拉伸或旋转像素"
去掉“请”，这是个开关标题，不是提示

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>请不要拉伸或旋转像素</b><p>对于富士 Super CCD 相机，显示倾斜 45 度的图"
对于富士 Super CCD 相机，显示倾斜 45 度的图像 => 自动将从富士 Super CCD 相机中导入的图像旋转 45 度

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "双线性的"
去掉“的”（你可以试想一下，在下拉菜单中有“的”是不是会很奇怪）

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>中值滤波器</b><p>对红-绿通道和蓝-绿通道进行插值之后，请在此设置将要应用"
去掉 -，红绿通道/蓝绿通道即可

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "自动的"
去掉“的”，同上

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "手动的"
去掉“的”，同上

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>高光</b><p>请在此挑选高光裁切模式：<p><b>纯白色</b>：将所有高光裁切为纯"
去掉“在此”

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "重构"
图像“重组”

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>亮度</b><p>指定输出图像的亮度级别。默认值（仅适用于 8 位模式）为1.0。"
1 前缺空格

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "<p><b>红色倍增器</b><p>请在此设置红色层的放大系数"
倍增器 => 增强

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "<p><b>蓝色倍增器</b><p>请在此设置蓝色层的放大系数"
倍增器 => 增强

2023-07-06 00:35 UTC, MingcongBai commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "ICC 文件(*.icc; *.icm)"
左括号前加空格，只有作快捷键用时左括号前不用加空格

2023-07-06 01:28 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p>如果启用，所有的 RAW 文件将以 16 位颜色深度解码，并且使用线性伽玛曲线。为"
* `为了防止在编辑器中渲染暗色图片，建议在此模式下启用色彩管理。` -> `为了防止在编辑器中图片渲染过暗，建议将色彩管理设置为此模式。`
* `a 99th-percentile white point` -> `此模式下的白点设置将导致亮度高于 99% 的颜色被裁切`

超过白点的颜色无法在色域中保存。

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"Method) 消除迷宫 (mazes)。"
我不确定这里的 mazes 说的是什么，但我感觉说的是 moire pattern，中文叫摩尔纹

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"像传感器所接收到的部分原始数据来内插完整的图像。也称为 CFA 插值或颜色重建，另"
这一段的翻译有点怪，可能需要补习一点上下文：

`A demosaicing algorithm is a digital image process used to interpolate a complete image from the partial raw data received from the color-filtered image sensor internal to many digital cameras in form of a matrix of colored pixels.` 一般来讲相机传感器上的每个像素前都有一个 colored filter （滤色片）。整个平面像素阵列上按一定的规律排列 RGB 三色的滤色片，RAW 记录的是传感器原始数据，也就是一堆单色像素的电平值。在常见的拜尔滤色 pattern 上，绿色像素数量是蓝色和红色数量的两倍，参考 https://zh.wikipedia.org/wiki/%E6%8B%9C%E7%88%BE%E6%BF%BE%E8%89%B2%E9%8F%A1

但一般人看图，看 jpeg / png / webp 的每个像素都有完整的三色通道，因此需要将相互交错的单色像素合并为单个 RGB/Lab 像素， 原文里的 `VNG` `PPG` ` AHD` 都是可以实现的算法之一。

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>白平衡模式</b><p>配置原始白平衡：<p><b>默认 D65</b>：使用标准日光 D65 "
* `配置原始白平衡` -> `配置 RAW 白平衡`
* `绿色级别值` -> `绿色电平值`

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "重构"
根据上下文我猜是“高光重建“里的“重建”

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>高光</b><p>请在此挑选高光裁切模式：<p><b>纯白色</b>：将所有高光裁切为纯"
* `以实现白色逐渐淡入的效果` -> `逐渐将更高亮度的颜色渐变为纯白色`

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>级别</b><p>指定重建高光级别。值越低，越偏向于白色，值越高，越偏向于其他"
可能应该和上面那个 "level" 保持一致

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>启用色差校正</b><p>通过给定的因子（通常为 0.999 至 1.001）放大原始的红"
原始 -> RAW 图层

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "<p><b>红色倍增器</b><p>请在此设置红色层的放大系数"
增强也不对，“缩放倍率”

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "<p><b>蓝色倍增器</b><p>请在此设置蓝色层的放大系数"
同上

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "修改"
“修正”

2023-07-06 01:59 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "内置的"
“内嵌”

2023-07-06 04:12 UTC, LWanTao commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "ICC 文件(*.icc; *.icm)"
好的，既然这里是GUI程序，也不是快捷键标记，那么是否修改为全角圆括号会更合适？（这样的话也就不需要在“件”的后方另外加空格了）

2023-07-06 05:08 UTC, LWanTao commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>白平衡模式</b><p>配置原始白平衡：<p><b>默认 D65</b>：使用标准日光 D65 "
关于您提出的第一点，其原文为`Configure the raw white balance`，其中`raw`与别处不同，没有使用大写，请问是否可以考虑进行翻译？

2023-07-06 05:16 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>白平衡模式</b><p>配置原始白平衡：<p><b>默认 D65</b>：使用标准日光 D65 "
个人认为可以，此处是在 raw 的数据上进行的白平衡而不是在映射后的 RGB 上操作，作为一个面向摄影的工具可能应该直接用术语

2023-07-06 05:33 UTC, LWanTao commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>白平衡模式</b><p>配置原始白平衡：<p><b>默认 D65</b>：使用标准日光 D65 "
好的，感谢指导，那我们就把这个部件中涉及 raw 的地方都翻译为 RAW。

2023-07-07 15:21 UTC, cthbleachbit requested changes

2023-07-07 15:21 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<qt><p>找不到命令 <b>%1</b>：<br>需要此二进制程序以提供对 RAW 文件格式的支"
“二进制程序”没改？

2023-07-07 15:21 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"进制程序的 %2 版本。由于此版本过旧，程序将无法正常运行。如果继续，您将无法处"
同上

2023-07-07 15:21 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"<p><b>请不要拉伸或旋转像素</b><p>自动将从富士 Super CCD 相机中导入的图像旋转 "
去掉“请”，这个 msgstr 下面还有一个“请”也是

2023-07-07 15:21 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"剪裁的值混合在一起，逐渐将更高亮度的颜色渐变为纯白色<p><b>重构</b>：使用级别"
改了选项的翻译之后，记得要让说明文本保持一致，“重构” -> “重建”

2023-07-07 15:21 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +msgstr "<p><b>红色增强</b><p>请在此设置红色层的放大系数"
“增强”不对，直接叫“系数”都好

2023-07-07 15:21 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"</b>：在 RAW 解码期间不使用输入色彩配置文件。<p><b>内置的</b>：若 RAW 文件内"
改了选项的翻译之后，记得要让说明文本保持一致，“内置的” -> “内嵌”

2023-07-07 18:40 UTC, cthbleachbit commented on TDE/libraries/libraries-libkdcraw-zh_Hans.po
> +"件格式的支持，您将无法处理 RAW 格式图像。请检查 libkdcraw 软件包在您电脑上"
“如果继续”怎么没了？

2023-07-08 18:50 UTC, cthbleachbit approved these changes

2023-07-10 05:32 UTC, merged