[WIP] TDE/tdebase: translate three components from upstream
AOSC-Dev/translations pull request #49
Opened 2023-07-12 12:02 UTC by LWanTao

In this PR, the following three components will be translated:

1. kdesktop - (100% with 8 fuzzy)
2. khotkeys-data - (100% with 8 fuzzy)
3. ktip - (on going)

**Sincerely appreciate those participated in the review and made suggestions!**

2023-07-21 04:15 UTC, MingcongBai requested changes

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "设置为主背景色"
去掉“置”

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "设置为次背景色"
同上；此外这两句是设置渐变的时候的界面语句吗？

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "设为墙纸(&W)"
感觉大陆书面语里一般还是叫桌面背景

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "image.png"
可以考虑翻译 image 部分，你定夺一下

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "在下面输入此图像的名称："
“在下面”其实没有必要，此外这里对应的功能是什么？不太好判断

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"无法正确注销。\n"
无法正常注销

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"无法联系会话管理器，您可以尝试通过 Ctrl+Alt+Backspace 组合键来强制退出；请注"
这句的翻译略显生硬，大概应该是“与会话管理器通信失败”

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"无法联系会话管理器，您可以尝试通过 Ctrl+Alt+Backspace 组合键来强制退出；请注"
此外，一般来说一个词组不应该切开换行，比如“注意”

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"%1 是一个文件，但 TDE 需要它是一个目录；将其移至 %2.orig 并创建目录吗？"
去掉“一个”，第二分句生硬（从“预期”之类的思路组织语言会更好，考虑到这里是一个类似 assert 条件无法满足的情况）

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"%1 是一个文件，但 TDE 需要它是一个目录；将其移至 %2.orig 并创建目录吗？"
“要将其”，因为这里的主语是用户“您”

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"%1 是一个文件，但 TDE 需要它是一个目录；将其移至 %2.orig 并创建目录吗？"
建议将分号改为句号

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "无法创建目录 %1；请检查权限或重新配置桌面以使用其它路径。"
同上，将分号改为句号

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "锁住会话（热键）"
锁屏（热键），这里主要考虑语言习惯

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "不需确认就注销"
注销时无需确认

同上，考虑一下句子的主语是谁

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "不需确认就关机"
同上

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "不需确认就重新启动"
同上

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "你选择删除一个系统图标"
一般用“您”，而且在后续翻译中应确保一致性；have chosen 的意思是用户已经尝试做了某件事情，所以应该是“您正尝试删除”

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "你可以在将来通过以下方式恢复这个图标"
这句话明显生硬，自己读读看，再组织语言

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "中的标签页"
启动下 TDE，确定这句的摆放位置是否有问题

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "特性"
行为

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "运行命令..."
GUI 程序应使用半个省略号，下面也有许多这样的问题

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "桌面设置控制模块的面板。"
控制桌面设置的面板，同样地，这些语句你应该试着自己读读，看看是否通顺

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "散列窗口"
不太确定这个翻译是否是最优解，你可以看看 Windows 是怎么翻译的

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "目录优先"
“目录靠前”可能更直白点

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "就地锁定"
锁定至当前位置，感觉“就地锁定”可能有点过于抽象

2023-07-21 04:15 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "就地锁定"
这个你判断下就好，仅供参考

2023-07-21 06:25 UTC, MingcongBai requested changes

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"<p>您已经选择了打开另外的桌面会话。<br>当前会话将被隐藏，并且会显示新的登录屏"
自己读一遍吧，问题很明显了……

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "开始新会话(&S)"
启动

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "以 png 格式另存为的文件名"
建议全大写 PNG

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "TDE 网站桌面"
网页桌面 *

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "要打开的 URL（如果没有指定，将从 kwebdesktoprc 中读取）"
如未指定则

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "显示一个 HTML 页面作为桌面的背景"
以 HTML 页面作为桌面背景

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "自动注销"
漏字了

2023-07-21 06:25 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "<qt>为了避免被注销，请移动鼠标或者按任意键以便恢复此会话。</qt>"
移动鼠标或按任意键即可继续使用本会话。

2023-07-21 09:05 UTC, LWanTao commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "设置为次背景色"
看了一下源码（[desktop.cpp:938](https://mirror.git.trinitydesktop.org/gitea/TDE/tdebase/src/branch/master/kdesktop/desktop.cpp)）

![image](https://github.com/AOSC-Dev/translations/assets/61775365/19adb17e-acaa-48b0-963e-0d7da2d9780c)

不是很懂，猜测可能是 主/次 二选一的情况？

2023-07-21 09:09 UTC, LWanTao commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "image.png"
看了一下源码（[desktop.cpp:974](https://mirror.git.trinitydesktop.org/gitea/TDE/tdebase/src/branch/master/kdesktop/desktop.cpp)）

![image](https://github.com/AOSC-Dev/translations/assets/61775365/72168084-d1a8-4a87-8ea0-6a25db69c095)

应该是对（用户未命名的）图像文件进行一个默认命名，所以确实可以进行翻译，我认为“未命名图像.png”挺好的。

2023-07-21 09:11 UTC, LWanTao commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "在下面输入此图像的名称："
源码同上，应该是先引导用户进行 “对图像文件的命名”。

但是这个 below 确实不知道是指 “文本输入框在下方”，还是指 “待命名的图像在下方”。

翻译为 “为该图像命名：” 感觉怪怪的？

2023-07-24 14:53 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "在下面输入此图像的名称："
> 但是这个 below 确实不知道是指 “文本输入框在下方”，还是指 “待命名的图像在下方”。

的确会有这个问题，你还是先安装下桌面然后看看情况。不过我觉得“输入此图像的名称”其实也足够好了

2023-08-01 14:28 UTC, MingcongBai requested changes

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "全部屏幕使用公共设置"
将设置应用于所有屏幕

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "如果您想要在 xinerama 模式中独立绘制每个屏幕，请启用该选项。"
xinerama => Xinerama

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"的桌面缓存，切换桌面将会更加平滑，但将以高内存占用为代价。"
如将缓存设置得更大，切换桌面时将更流畅，但会占用更多内存

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"在这里您可以设置背景的不透明度（0-100），合成管理器以此为基础进行渲染。"
0 至 100；0 ~ 100

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"一点，但您也无法将文件拖曳至桌面。"
但您将无法将文件拖拽至桌面

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "允许桌面窗口中的应用程序"
允许在桌面窗口中运行程序

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"请选中该选项。如果您在 Netscape 这样需要检查 root 窗口的运行实例的应用程序时"
请打开该选项

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "自动排列图标"
自动对齐图标

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "优先排序目录"
目录靠前

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "定义所使用的终端应用程序。"
定义要使用的终端应用程序

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "您可以通过在桌面背景上使用鼠标滚轮来切换虚拟桌面。"
通过在桌面背景上使用鼠标滚轮来切换虚拟桌面。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "您可以设置当您在桌面上单击鼠标左键时所触发的事件。"
同理，去掉所有“您可以”

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "图标标签所用的背景颜色"
去掉“所用”

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"选中此处可启用桌面字体的阴影轮廓，可以提高桌面文本在类似颜色背景下的可读性。"
打开此选项可启用桌面字体的阴影轮廓，以提高桌面在相似颜色背景下的可读性。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"目录内文件的排序依据等。建议您不要随意更改或删除，除非您完全了解这些文件。</"
把“除非”放到主句，其余部分放到从句

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "通过按住 Ctrl 键并滚动鼠标滚轮以改变间距"
按住 Ctrl 键并滚动鼠标滚轮以改变间距

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "启用屏幕保护程序。"
该选项启用屏幕保护程序

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"显然是会启动显示节能（模式），同时暂停屏幕保护程序。然而，也存在一些屏幕保护"
在屏幕启动节能模式时暂停屏幕保护程序。然而有一些屏幕保护程序会执行一些实用计算任务，因此不应暂停这类屏幕保护程序。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "自动完成（Autocomplete）显示可用的应用程序(&a)"
自动补全

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"<qt>启用后，系统在自动完成区显示可用的应用程序。\n"
启用后，系统将列出自动补全得出的应用程序列表

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "自动完成使用文件系统而不是历史记录(&F)"
使用文件系统而非历史记录进行自动补全(&F)

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "在这里输入您指定用户的密码。"
在这里输入所指定用户的密码

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"如果您要运行的程序是文本模式的，请勾选该选项。通过这样做，程序将运行在模拟终"
“通过这样做”明显不符合中文习惯

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "以不同的用户运行(&U)"
以另一用户的身份运行

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +"输入您要执行的命令或您要打开的资源的地址，可以是一个远程 URL，如“www.kde."
…… 支持远程 URL，如……，或本地 URL，如……

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "基本的 Konqueror 手势。"
基本 Konqueror 手势。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "简单的操作"
简单操作

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "打印屏幕"
截图行为

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "当 PrintScren 键被按下时，启动 KSnapShot。"
按下 PrintScrn 键时启动 KSnapShot。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "打印窗口"
窗口截图行为

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"包含的所有操作都被默认为禁用。）"
括号在句号前，此处只需要一个括号 ……（）。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"“回车”（即新的一行）                Enter 或 Return\n"
用 \t 替换此处的翻译

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "在按下 Ctrl+Alt+T 之后，将会运行 Konsole。"
在按下 Ctrl+Alt+T 之后，将会运行 Konsole。

=>

按下 Ctrl+Alt+T 时，启动 Konsole。

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"Qt Designer 使用 Ctrl+F4 来关闭窗口（也许是因为 MS Windows 也这样做*耸*）。但"
*耸* 有点不地道，可以去掉或者用更地道的方式写，比如 `¯\(ツ)/¯`

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +msgstr "在 Qt Designer 中 重映射 Ctrl+W 快捷键为 Ctrl+F4"
多了个空格

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"上，您也可以控制它。\n"
想办法去掉“它”

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"去使用其他浏览器了吧 >;) 。\n"
同上，颜文字可以考虑换成更地道的

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"去使用其他浏览器了吧 >;) 。\n"
甚至可以“（笑）”

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"键。如果您不想进行手势操作，只是想粘贴选区，那么请点击鼠标中键。（您也可以在"
句号和括号的摆放问题，见上

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"向右和向左后移动 - 前进 (ALt+Right)\n"
半角括号

2023-08-01 14:28 UTC, MingcongBai commented on TDE/tdebase/tdebase-khotkeys-data-zh_Hans.po
> +"Konqueror（类包含“konqueror”）时才会生效。"
手势类中包含 "konqueror"

2023-08-01 16:36 UTC, LWanTao commented
@MingcongBai 

Uploaded to the upstream, ready for being merged ( •̀ ω •́ )✧.

2023-08-03 15:02 UTC, MingcongBai requested changes

2023-08-03 15:02 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "废弃"
已弃用（这里大概是放在某个括号或者补充说明里的）

2023-08-03 15:02 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "等待 kded 完成数据库构建"
正等待

2023-08-03 15:02 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "<p>这是您桌面图标之间的最小（像素）距离。</p>"
这是您桌面图标之间的最小距离（以像素为单位）。

2023-08-03 15:02 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-zh_Hans.po
> +msgstr "以实时调度方式运行(&S)"
以实时调度优先级运行(&S)

“实时”是 *nix 系统中最高调度优先级

2023-08-03 17:50 UTC, merged