[WIP] TDE/tdebase: translating five components from upstream
AOSC-Dev/translations pull request #51
Opened 2023-08-03 19:31 UTC by LWanTao

In this PR, I pulled the following five components from upstream.

1. kdesktop-desktop-files -> 100%
2. kdesktop-icons -> 100%
3. konsole -> In progress
4. konsole-events -> In progress
5. konsole-desktop-files -> In progress

**Sincerely appreciate those participated in the review and made suggestions!**

2023-08-13 14:49 UTC, MingcongBai requested changes

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-desktop-files-zh_Hans.po
> +msgstr "夜色中的岩石 by Tigert"
这个翻译让我很头疼，我想建议去掉 by Tigert 不过这样就不完整了，你有啥点子不

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-desktop-files-zh_Hans.po
> +msgstr "人行道"
这个叫“街砖”更好

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-desktop-files-zh_Hans.po
> +msgstr "花"
花朵，统一两个字吧

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-desktop-files-zh_Hans.po
> +msgstr "花"
繁花，也许也不错

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "主页"
这个大概指的是个人文件，或称“主文件夹”

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "包含个人文件"
少了主语

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "我的计算机"
“我的电脑”就好

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "包含个人文件"
比如“此文件夹包含——”

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "包含个人文档"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "网络"
“网上邻居”（不需要规避 Windows 翻译

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "访问系统位置"
总觉得怪怪的，是什么位置？

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "新建相机"
添加相机（哪有新建相机一说

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "新建 CD-ROM 设备"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "刻录机设备…"
“设备”是多余的

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "CD-ROM 设备…"
“CD-ROM 光驱”会更好

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "DVD-ROM 设备…"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "软驱设备…"
同上“设备”是多余的

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "硬盘设备…"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "MO 设备…"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "NFS…"
“NFS 远程文件夹”这样具体写出来可能会好理解一些

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "应用程序链接…"
这就是“快捷方式”

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "地址链接 (URL)…"
网址

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "ZIP 设备…"
一般叫“Zip 驱动器”

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "ZIP 设备…"
这里原文的 ZIP 全大写其实不准确，可以给上游报告下，参考：

https://zh.wikipedia.org/zh-hans/Zip_Drive

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "包含已删除的文件"
缺少主语，同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "浏览 Web"
浏览互联网

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-kdesktop-icons-zh_Hans.po
> +msgstr "模板"
文件模板

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "用以打开 Shell 的文件类型"
用于

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "终端仿真器"
现在的用词习惯叫“终端模拟器”

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "新建 Midnight Commander"
的什么？

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "Shell"
我感觉 Shell 可以翻译为“命令提示符”，不过这个你定夺下

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "Root Midnight Commander"
Root 这里指的大概是用户

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "Root Midnight Commander"
最好确定下，我根据下一条猜的

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "在此打开终端"
此处

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-desktop-files-zh_Hans.po
> +msgstr "5 号 Shell"
笑死，6 呢（

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "可见会话中发生的响铃"
去掉“的”，这里是描述现象

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "可见会话中发生的响铃"
“发生的”大概也是多余的

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "不可见会话中发生的响铃"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "监视会话存在活动"
受监视会话

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "监视会话存在活动"
注意时态

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "检测到监视会话中有活动"
同上

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "监视会话不存在活动"
“没有活动”不就好了

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "会话以非零状态完成"
“非零状态”其实可以直接译作“错误状态”

2023-08-13 14:49 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-events-zh_Hans.po
> +msgstr "会话以非零状态退出"
同上

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"您正尝试将一个（或多个） Ctrl+<按键> 组合用作快捷键。这样做将导致这些按键组合"
自己试着读读这句话，是否符合语言习惯，是否顺口？

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"请指定您要存放此文件的文件夹："
请指定用于……

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "开始将文件下载到指定文件夹。"
已开始？这里是提示还是按钮？

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "启动登录 shell"
如果你最后决定用 Shell，那么确保 S 有大写

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"指定 TERM 环境变量\n"
大概可以不换行

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "列出可用的标签"
出现歧义了，keytab 和 Tab（标签页）

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "用给定的会话类型启动"
这句话是什么意思？

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "用给定的会话配置启动"
同上

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "启用扩展的 DCOP TQt 函数"
“扩展的”可能不是很好，去掉“的”也许通顺些

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "执行尖括号中的命令，而非作为 shell 脚本运行"
见上关于 Shell 的批注

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "维护者，修复了众多 Trinity 中的漏洞"
Bugfixes 是问题修复，不是漏洞修复

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "维护者，修复了众多 Trinity 中的漏洞"
既然下面是“前任”，那么这句加上“现任”吧

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "修复漏洞与改进"
同上，bug 不是漏洞

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "修复漏洞"
同上

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "Solaris 支持和历史"
Solaris 支持和历史记录特性

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "改善启动速度，修复漏洞"
同上，关于 bug 的翻译问题

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "合适的标志设计 (decent marking)"
确定下这里的 marking 指的是什么（调查下 Changelog)

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "工具栏和会话名"
Partification?

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "工具栏和会话名"
这里大概说的是特性，所以加上“特性”或“功能”结尾会好些

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "透明"
同上，这里指代的大概是特性

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"main.C 的大部分内容都是由 kvt 贡献的\n"
大概不用换行

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"main.C 的大部分内容都是由 kvt 贡献的\n"
而且这句话不通顺

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "配色方案和选区的改进"
配色方案“支持”（见上）

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"感谢其他未留名的贡献者们，\n"
这里稍微改改，不通顺；此外，去掉“我”

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "您不能同时使用 -ls 和 -e。\n"
去掉“您”

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "预期为 --vt_sz <#列>x<#行> 例如 80x40\n"
这里就注意不要用乘号替代了，因为是命令参数

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"Konsole 无法打开 PTY（伪终端），很可能是因为 PTY 设备配置不当。Konsole 需要获"
“配置不当”这个翻译很棒，别的程序也应该参考

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"Konsole 无法打开 PTY（伪终端），很可能是因为 PTY 设备配置不当。Konsole 需要获"
“配置不当”这个翻译很棒，别的程序也应该参考

2023-08-13 15:14 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"Konsole 无法打开 PTY（伪终端），很可能是因为 PTY 设备配置不当。Konsole 需要获"
“配置不当”这个翻译很棒，别的程序也应该参考

2023-08-13 15:19 UTC, MingcongBai requested changes

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"得对 PTY 设备的读/写权限。"
去掉“获得”

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"得对 PTY 设备的读/写权限。"
有这个权限才能怎样？把这句合并到上一句中（改改句式）

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "会话“%1”以状态 %2 结束。"
exit 不是结束，是退出

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "会话“%1”已结束并吐核 (dumped core)，信号 %2。"
已崩溃？

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "浅色背景与黑字"
这里的浅色是什么色

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "浅黄背景与黑字"
浅黄底黑字，这样简洁些

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "Ugly 1"
这个是可以翻译的

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "Midnight Commander 配色（绿色调，透明）"
绿色调，带透明

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "vt100（年代久远）"
（仿古体验）

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "<p>…按下 Ctrl+Alt+N 组合键将启动新的标准会话。\n"
以启动新的标准会话（另外结尾是问号，重新检查下）

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "<p>…用 Ctrl+Alt+M 组合键激活菜单。\n"
“组合键”后统一加一下“以”

2023-08-13 15:19 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"中设置标签选项。\n"
上面这些长句多有不通顺的情况：

1. 自己朗读一遍，看看是否自然
2. 尽量去掉“您”、“它”、“正”和“被”

2023-08-13 17:50 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "<p>…按下 Ctrl+Alt+N 组合键将启动新的标准会话。\n"
这一块（1138 行一直到结尾）都是 tips，上方都有一句话是“Do you know?”，这也解释了为什么开头是省略号。我觉得可能翻译成陈述句比较合适，同时考虑到语境，用“将”或者“可以”应该更合适？

2023-08-13 17:53 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "在 %1 上运行 Screen"
应该是指 Linux 命令行中的“Screen”应用，而且似乎“_:”后面一行的内容是可以不用翻译的？（参考 26 行）

2023-08-13 17:57 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "Ugly 1"
丑陋的 1？（不是

2023-08-13 18:02 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +"main.C 的大部分内容都是由 kvt 贡献的\n"
![image](https://github.com/AOSC-Dev/translations/assets/61775365/41eeb764-ca82-4c7d-96ae-a89fac193335)

这里是致谢内容，原文确实挺潦草的...或许可以这样翻译？：

```
1. kvt 贡献了 main.C 的大部分内容
2. 整体的改进
```

2023-08-14 02:08 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "<p>…按下 Ctrl+Alt+N 组合键将启动新的标准会话。\n"
对

2023-08-15 11:47 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "在书签处新建 Shell"
大概是：

- 新建书签：将当前所在路径保存为书签
- 在书签处新建 Shell：在保存的特定路径新建 Shell

2023-08-15 12:51 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "列出可用的标签"
搞明白了，此 keytab 指的是“键盘响应风格”，

```
The keytabs offered in the Options/Keyboard menu are  
taken from from configurations files with a *.keytab  
pattern either located in $TDEDIR/share/apps/konsole  
or ~/.trinity/share/apps/konsole.

Keytabs allow to configure the behavior of konsole  
on keyboard events, especially for functions keys.  
Please have a look into the README.keyboard file, too.

```

> 来源：[tdebase/konsole/other/README.KeyTab](https://mirror.git.trinitydesktop.org/gitea/TDE/tdebase/src/branch/master/konsole/other/README.KeyTab)

2023-08-15 13:05 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "合适的标志设计 (decent marking)"
我似乎找不到，确认了一下其他翻译，其中唯一没有直译的为“俄语”，转译为中文是“选区与标记”，我觉得可以参考？

2023-08-15 13:06 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "历史(&O)…"
“终端所有操作”的历史记录

2023-08-21 13:20 UTC, MingcongBai requested changes

2023-08-21 13:20 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "大小：XXX * XXX"
为何不继续使用乘号？

2023-08-21 13:20 UTC, MingcongBai commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "终端窗口大小（列*行）"
同上

2023-08-21 13:42 UTC, LWanTao commented on TDE/tdebase/tdebase-konsole-zh_Hans.po
> +msgstr "大小：XXX * XXX"
抱歉，我把星号误解为乘号了。

这里原文是字母 x（另外还有关于 Zip 的大小写问题），我试着写封 Email 给上游 i18n 相关的开发人员~

2023-08-22 14:49 UTC, merged