[WIP] TDE/tdebase: translate three components about kicker* from upstream
AOSC-Dev/translations pull request #53
Opened 2023-08-31 13:24 UTC by LWanTao

In this PR, I pulled the following **three** components from upstream.

|Component Name|Translation Status|
|:-|:-|
|kicker | Help Wanted (100% with 26 fuzzy) |
|kickermenu_kate | Review Needed (100%) |
|kicker-desktop-files | Help Wanted (100% with 2 fuzzy) |

2023-08-31 14:12 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-desktop-files-zh_Hans.po
> +msgstr "直接访问存储介质"
同上

2023-08-31 14:12 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-desktop-files-zh_Hans.po
> +msgstr "直接访问存储介质"
比如什么，快捷访问……？

2023-08-31 14:27 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-desktop-files-zh_Hans.po
> +msgstr "您最近所使用文档的菜单"
您最近使用过的文件列表

2023-09-03 04:23 UTC, MingcongBai requested changes

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "配置面板(&C)..."
省略号不对

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "报告错误(&B)…"
报告问题 *

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "切换至 Kickoff 菜单风格"
这里的“风格”是多余的

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "非可执行"
不可执行

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "目录：/)"
同上，确定下是状态还是动词

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "- 要搜索多个可选项，请使用 OR。"
OR 表达式

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "- 要排除搜索指定项，请在其前面使用减号。"
给个括号加个范例

2023-09-03 04:23 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "- 可以使用大写或小写字母。"
不区分大小写

2023-09-03 05:47 UTC, MingcongBai requested changes

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "确定要重置计算机并安装 Microsoft Windows 系统吗"
重启？

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "从收藏移除"
收藏，还是书签？统一一下

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "进阶"
还是“高级设置”之类的更符合习惯

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "媒体"
确定下是媒体还是存储介质

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "冻结"
冻结会话

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "将计算机置于软件空闲模式"
挂起所有进程，将计算机置于空载状态

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "挂起至 RAM"
将会话挂起至内存并睡眠

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "挂起至磁盘"
将会话挂起至硬盘并睡眠

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "挂起"
睡眠会更好

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "面板隐藏动效的速度"
动画 *

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "为面板隐藏启用动态效果"
动画

2023-09-03 05:47 UTC, MingcongBai commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +"如果命令是一个命令行应用程序，而您想要在其运行时看到输出，请选择此选项。"
前两节有点啰嗦了，“一个”和“而”这些没了其实都没影响，可以推敲下

2023-09-03 12:46 UTC, LWanTao commented on TDE/tdebase/tdebase-kicker-desktop-files-zh_Hans.po
> +msgstr "Swallow 小程序"
不知道，目前在系统中似乎处于隐藏状态，也暂时没有看到与之相关的其他翻译内容

2023-09-03 13:00 UTC, LWanTao commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "浏览：%1"
在系统中找不到出处，从源码看：变量“%1”是指路径，且后续代码进行了读写操作，所以应该是动词。

2023-09-03 13:15 UTC, LWanTao commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "%1（%3 的前 %2 个）"
例：在搜索框中进行搜索，结果有 18 个，但只展示前 10 个，即 top 10 of 18。

2023-09-03 13:23 UTC, LWanTao commented on TDE/tdebase/tdebase-kicker-zh_Hans.po
> +msgstr "目录：/)"
在系统中找不到，通过代码猜测是名词“目录/路径”。

2023-09-20 09:53 UTC, MingcongBai approved these changes

2023-09-20 11:09 UTC, merged